name: grisette-monad-coroutine
version: 0.2.0.0
synopsis: Support for monad-coroutine package with Grisette
description: Orphan instances and wrappers for monad-coroutine package with Grisette.
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-monad-coroutine
copyright: "2021-2024 Sirui Lu"
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base > 4.14 && < 5
  - grisette >= 0.4.0 && < 0.5
  - mtl >= 2.2.2 && < 2.4
  - transformers >= 0.5.6.2 && < 0.7
  - monad-coroutine >= 0.9.0.4 && < 9.3

flags:
  {
    optimize:
      {
        description: "Compile with O2 optimization",
        manual: False,
        default: True,
      },
  }

when:
  - condition: flag(optimize)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette-monad-coroutine
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6 && < 1.7
      - QuickCheck >= 2.13.2 && < 2.15
